In [1]:
import crypten

In [2]:
import torch

In [3]:
crypten.init()

In [4]:
x = torch.rand((128,10))

In [5]:
x_enc = crypten.cryptensor(x)

In [6]:
import crypten.mpc as mpc
import crypten.communicator as comm

In [8]:
import torch.nn as nn

In [24]:
class SigModel(nn.Module):
    def __init__(self, comp=0.5, nu = 1.0):
        super(SigModel,self).__init__()
        self.comp = comp
        self.nu = nu
    def forward(self, x):
        max_val = x.max(dim=1)[0]
        cond_in = torch.sigmoid(self.nu*(self.comp-max_val))
        return cond_in

In [89]:
def inference_sigmodel(x,comp=0.5, nu=1.0):
    max_val = x.max(dim=1)[0]
    cond_in = (nu*(comp-max_val)).sigmoid()
    return cond_in
def inference_comp(x,comp=0.8):
    max_val = x.max(dim=1)[0]
    cond_in = max_val>comp
    return 1-cond_in

In [90]:
class CompModel(nn.Module):
    def __init__(self, comp = 0.5):
        super(CompModel, self).__init__()
        self.comp = comp
    def forward(self,x):
        max_val = x.max(dim=1)[0]
        cond_in = max_val>self.comp
        return cond_in

In [97]:
0.9**10


0.3486784401000001

In [91]:
crypten.nn.Sigmoid

crypten.nn.module.Sigmoid

In [92]:
x.sigmoid()

tensor([[0.6921, 0.7249, 0.5323,  ..., 0.5598, 0.6278, 0.7278],
        [0.5908, 0.6544, 0.7073,  ..., 0.5471, 0.6873, 0.7035],
        [0.5119, 0.5003, 0.7055,  ..., 0.7015, 0.5170, 0.7010],
        ...,
        [0.5350, 0.5219, 0.6482,  ..., 0.5678, 0.5608, 0.6697],
        [0.5759, 0.6806, 0.6750,  ..., 0.5110, 0.6858, 0.5933],
        [0.7031, 0.7036, 0.5597,  ..., 0.6572, 0.5977, 0.6587]])

In [93]:
sigmodel = SigModel()
compmodel = CompModel()

In [94]:
enc_out = inference_sigmodel(x_enc)

In [95]:
enc_out2 = inference_comp(x_enc)

NotImplementedError: CrypTen does not support torch function <built-in method logical_not of type object at 0x7f38506560a0>.

In [85]:
enc_out.get_plain_text()-inference_sigmodel(x)

tensor([ 6.3598e-05, -5.3734e-04,  2.1085e-04, -4.3213e-04,  2.1401e-04,
         7.3045e-05, -3.9920e-04,  4.1455e-05,  1.4484e-05, -2.1562e-04,
         2.8715e-04,  3.8576e-04, -2.0409e-04, -4.1789e-04, -1.8051e-04,
        -3.1963e-04,  6.7648e-04,  1.9914e-04, -2.9045e-04, -1.4693e-05,
         1.0505e-04,  5.8490e-04,  2.4995e-04,  5.0205e-04, -3.0902e-04,
         3.7262e-04, -3.2011e-04,  9.4035e-04, -1.1167e-04, -8.1211e-05,
         3.5954e-04,  1.6189e-04,  3.1504e-04,  3.7196e-04, -3.7119e-04,
         5.1379e-04,  1.3083e-05,  3.0506e-04, -3.3519e-04, -6.5297e-05,
        -2.2310e-04,  3.2163e-04,  1.7464e-04,  4.0972e-04,  2.7409e-04,
         4.7335e-04,  4.1169e-04, -2.9656e-04, -4.5753e-04, -4.7630e-04,
         3.2195e-04,  5.0902e-05, -2.5147e-04, -2.0283e-04, -6.0967e-04,
        -5.1704e-04,  6.0838e-04,  3.6737e-04,  4.7401e-04, -2.2274e-04,
        -2.1195e-04, -1.0672e-04, -2.6259e-04,  2.0248e-04, -5.8740e-04,
         2.1046e-04, -3.5858e-04,  8.6486e-05, -5.5

In [86]:
enc_out2.get_plain_text()

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 3, 3, 0,
        0, 0, 0, 3, 0, 0, 0, 0, 3, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 0,
        0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 3, 3, 3, 0])